package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/PhilippWegner/hochschule-bochum-masterarbeit/microservices/graphql-plc-api/database"
	"github.com/PhilippWegner/hochschule-bochum-masterarbeit/microservices/graphql-plc-api/graph/model"
)

// Plcs is the resolver for the plcs field.
func (r *queryResolver) Plcs(ctx context.Context, machine string, time string, limit int, filter *model.IdentifierFilterInput) ([]*model.Plc, error) {
	return influxdb.GetPlcs(machine, time, limit, filter)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

var influxdb = database.ConnectInfluxdb()
