package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/PhilippWegner/hochschule-bochum-masterarbeit/microservices-with-graphql/graphql-api/database"
	"github.com/PhilippWegner/hochschule-bochum-masterarbeit/microservices-with-graphql/graphql-api/graph/model"
)

// CreateStates is the resolver for the createStates field.
func (r *mutationResolver) CreateStates(ctx context.Context, input []*model.CreateStatesInput) ([]*model.State, error) {
	return influxdb.CreateStates(input)
}

// Plcs is the resolver for the plcs field.
func (r *queryResolver) Plcs(ctx context.Context, machine string, time string, limit int, filter *model.IdentifierFilterInput) ([]*model.Plc, error) {
	return influxdb.GetPlcs(machine, time, limit, filter)
}

// States is the resolver for the states field.
func (r *queryResolver) States(ctx context.Context, machine string, limit int) ([]*model.State, error) {
	return influxdb.GetStates(machine, limit)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var influxdb = database.ConnectInfluxdb()
